name: mobildershane
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter: 
    sdk: flutter
    

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  cloud_firestore: ^3.1.1
  firebase_core: ^1.10.1
  google_fonts: ^2.1.0
  getwidget: ^2.0.4


flutter: 
  uses-material-design: true

